name = "Magia2"
author = "dealere"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be48a37998acc64a282f91025123f4f4bc7b364af2a660b61bc635dde615b36a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
