name = "Hotel"
author = "dealerke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09589c8254617a0ac4a73c78beff8a3087e679b48dc8b59ae546be6274d3dae1"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
