name = "Hotel"
author = "dealerke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e43cd6101ce38b108a6f31095cd0144544ad8a3bc89fc2db1952a791efe62872"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
