name = "Hotel"
author = "dealerke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "359614f8e244a7a2cb422f0a5bfc8277df20b66100d931672c2b00e5582cdf9e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
